server:
  port: 8080
  tomcat:
    max-threads: 500
    max-connections: 6000
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
  compression:
    enabled: true
    mime-types: text/html,text/javascript,text/xml,text/plain
    min-response-size: 5MB

logging:
  config: classpath:log/logback-spring-dev.xml
  level:
    com.spdb.apix: error

mybatis:
  mapper-path: /mapper/**.xml
  package-path: com.greenhome.mapper
  config-path: mybatis-config.xml

spring:
  mvc:
    async:
      request-timeout: 60s
  redis:
    timeout: 6000ms
    password: apiBank@2020
    lettuce:
      pool:
        max-active: 100
        max-wait: 6000
        max-idle: 100
        min-idle: 50
    #sentinel哨兵配置
    sentinel:
      master: mymaster
      nodes: 10.136.64.106:26380,10.136.64.107:26380,10.136.64.108:26380
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/GreenHome?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
