server:
  port: 8080
  servlet:
    context-path: /manage
  tomcat:
    max-threads: 500
    max-connections: 6000
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
  compression:
    enabled: true
    mime-types: text/html,text/javascript,text/xml,text/plain
    min-response-size: 5MB

logging:
  config: classpath:log/logback-spring-dev.xml
  level:
    com.spdb.apix: error

mybatis:
  mapper-path: /mapper/**.xml
  package-path: com.greenhome.mapper
  config-path: mybatis-config.xml

spring:
  mvc:
    async:
      request-timeout: 60s
  redis:
    #    host: 192.168.1.100
    #    port: 6385
    timeout: 6000ms
    password: apiBank@2021
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: 6000
        max-idle: 100
        min-idle: 1
    cluster:
      nodes:
        #地址要和redis配置中bind地址一致
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
    #sentinel哨兵配置
      #sentinel:
      #master: mymaster
      #nodes: 10.136.64.106:26380,10.136.64.107:26380,10.136.64.108:26380

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/GreenHome?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

swagger2:
  #swagger的配置信息
  title: GreenHome RESTful APIs
  description: Bit by bit life, heart perception, green ocean, quiet and comfortable
  termsOfServiceUrl: http://www.greenhome.com
  license: smart_joker~
  version: v1.0
  packageScan: com.greenhome.manage.controller
