apiVersion: v1
kind: Service
metadata:
  namespace: greenhome
  name: service-gateway
  labels:
    name: service-gateway
spec:
  type: NodePort      #使用宿主机端口，能够访问各Node的外部客户端通过Node的IP和端口就能访问服务器
  ports:
    - port: 18080          #这里的端口和clusterIP(10.97.114.36)对应，即10.97.114.36:80,供内部访问。
      targetPort: 18080  #端口一定要和container暴露出来的端口对应，nodejs暴露出来的端口是8081，所以这里也应是8081
      protocol: TCP
      nodePort: 32323   # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: gateway          #这里选择器一定要选择容器的标签，之前写name:kube-node是错的